### ISSUE TITLE
Rendering On SSR

### ISSUE THREAD

**Issue by AmoDinho** [pimp-my-book/umqombothi-component-library#13]
I am struggling to integrate a react-component library in my NextJS setup.

What I've done is to in corporate '@zeit/next-css' in my next.config.js, as well using 'next-transpile-modules':

```
module.exports = withCSS({ })


module.exports = withTM({
    transpileModules: ['umqombothi-component-library']
})
```

This is the final error message I get:

```
[ error ] ./node_modules/umqombothi-component-library/src/index.css 11:5
Module parse failed: Unexpected token (11:5)
You may need an appropriate loader to handle this file type.
|  */
|
> html {
|   line-height: 1.15; /* 1 */
|   -webkit-text-size-adjust: 100%; /* 2 */
ModuleParseError: Module parse failed: Unexpected token (11:5)
You may need an appropriate loader to handle this file type.
|  */
|
> html {
|   line-height: 1.15; /* 1 */
|   -webkit-text-size-adjust: 100%; /* 2 */
    at handleParseError

```

The reason I'm using 'next-transpile-modules' because I got:

```
node_modules\umqombothi-component-library\src\index.js:1
(function (exports, require, module, __filename, __dirname) { import PrimaryButton  from "./components/buttonComponent/PrimaryButton"
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.umqombothi-component-library

```

This is how I'm also importing the lib:

```
//index.js

import {PrimaryButton} from 'umqombothi-component-library'


const index= () => (
    <div>
        <h1>Add a Book to your inventory</h1>
        <PrimaryButton
                   text="Hello World"
                   />
    </div>
)

export default index

```
Here is the [component-library's repo](https://github.com/pimp-my-book/umqombothi-component-library) maybe I'm messing up in here?

**Comment by AmoDinho** [comment]
Hi everyone, 

I'm trying to use a component library but it gives me the following error: 

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

I'm importing the component like a default export into next like such:

```
import  HeadingOne  from "umqombothi-component-library";

```

Even when I import it as  a named export I still get the same error.

This is how I am exporting the component from the component library:
```
export { default as HeadingOne } from './components/typography/HeadingOne'

```

Here is the [Codesandbox ](https://codesandbox.io/s/hello-world-xmu4s)for reproduction and the [component library](https://github.com/pimp-my-book/umqombothi-component-library/tree/feature/rollup).

**Comment by AmoDinho** [comment]
I fixed this by changing which files are exported.
